### ISSUE TITLE
Нерабочая ссылка на Chrome Web Store

### ISSUE THREAD

**Issue by juvirez** [yangirov/yandex-music-app-linker#1]
>Установите расширение из [Chrome Web Store](https://chrome.google.com/webstore/detail/yandex-music-app-linker/afcbcmeeninkbbibemgngnendopcpedb)

Ссылка ведёт на 404 ошибку.

**Comment by yangirov** [comment]
Привет! Да, ссылка не работала, т.к. модерация хрома отклонила разрешение потому что слишком маленькое описание было. Поправил. Теперь ссылка работает.
